services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 3001:8000
    depends_on:
      init:
        condition: service_completed_successfully
      chromadb:
        condition: service_started
    environment:
      - BOT_INIT_MESSAGE=Bonjour, je suis le chatbot de l'Université de Lausanne. Comment puis-je vous aider ?
      - CHROMADB_PORT=8000
      - CHROMADB_HOST=chromadb
      - CHROMADB_COLLECTION_NAME=students_autumn
      - USE_STREAM=True
    networks:
      - net

networks:
  net:
    external: true
